ALTER TABLE clients ADD COLUMN cpf TEXT NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN birth_date TEXT NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN notes TEXT NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN preferences TEXT NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN allergies TEXT NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN blocked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE clients ADD COLUMN blocked_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE clients ADD COLUMN updated_at INTEGER;
ALTER TABLE appointments ADD COLUMN no_show INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS clients_tenant_cpf_unique
  ON clients (tenant_id, cpf) WHERE cpf != '';
